### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by TheBaconSpace** [Leviathan5/BeamSoundlyInteractive#1]
Hey Can You Add Custom Spark Adding wat if People Want Them 0 :+1:

**Comment by DeekyJay** [comment]
Sadly, sparks are set on the Beam app strictly. If you'd like, you have the ability to create your own app with 16 buttons, where you can change the names and sparks yourself. I wish I could do this programmatically but it's currently not possible!

**Comment by ProbablePrime** [comment]
Totally is possible @Leviathan5 Let's get together and discuss it.
