### ISSUE TITLE
Difficult to find the right place to click and drag to move the "application" window

### ISSUE THREAD

**Issue by brumoen** [Leviathan5/BeamSoundlyInteractive#14]
It's difficult to find the right place to click & drag to be able to move the window, you have to click in a small area right above the Soundwave Interactive logo and your profile picture. It's a very narrow line instead of being able to click in the whole "logo bar" field.

**Comment by DeekyJay** [comment]
Yeah this is definitely something I plan to tweak. I've added it to my trello board. 👍

**Comment by DeekyJay** [comment]
Update coming soon that expands the drag zone bar for essentially the whole nav bar (dead zone being the user info and window controls)

**Comment by DeekyJay** [comment]
#17 Resolves this issue. 0.9.6 has been released.
