### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by BossFister** [Leviathan5/BeamSoundlyInteractive#15]
Just Installed, I had been using the Soundly Interactive Board previously. When I click the Login button it just brings up a white blank window and nothing happens.

**Comment by DeekyJay** [comment]
Hi @BossFister , are you able to navigate to beam.pro in a browser like Chrome?

**Comment by BossFister** [comment]
Sorry, I forgot to post here about it after I figured it out. I was having problems with my antivirus and it was causing connection issues. It works now. Thanks for the reply!

**Comment by DeekyJay** [comment]
Glad you got it sorted :) Enjoy!
