### ISSUE TITLE
Click and drag is frustrating

### ISSUE THREAD

**Issue by lfkeitel** [Leviathan5/BeamSoundlyInteractive#16]
Click-and-drag is typically expected to be instant. The moment I move my mouse the item drags. With the 0.9.5 beta I have to click, wait, and then drag. Would there be a way to detect mouse movement instantly and drag rather than wait for the animation to finish?

**Comment by DeekyJay** [comment]
Hi there, the update coming out soon will resolve this issue. Dragging will now be triggered based on how far your mouse has travelled while clicked down. This should make it clear for when the user wants to click on it just to edit, and when they want to drag it to the board

**Comment by lfkeitel** [comment]
Awesome to hear that, I look forward to trying it out.

**Comment by DeekyJay** [comment]
#17 resolves this issue. 0.9.6 has been released.
