### ISSUE TITLE
No way to stop sound without closing app.

### ISSUE THREAD

**Issue by ouTPhaze** [Leviathan5/BeamSoundlyInteractive#18]
Three things:

#1 You can't stop the sound from within the app.

#2 Disconnecting doesn't stop sound (it should).

#3 Windows Volume Mixer shows it as a HUGE icon covering all controls, you can still "use" the controls, but you can't see them: 
![image](https://cloud.githubusercontent.com/assets/433807/20731311/79ca064a-b64f-11e6-8d18-c15a94391bef.png)

A "Halt all sounds" button would be very nice, preferably one available on all pages of the application.

**Comment by DeekyJay** [comment]
This will be resolved in the next update.

**Comment by DeekyJay** [comment]
Resolved with #19. In update 0.9.7
