### ISSUE TITLE
Login will not work for Microsoft, Discord, Twitter accounts

### ISSUE THREAD

**Issue by ScalySquash50** [Leviathan5/BeamSoundlyInteractive#25]
It appears that something has gone wrong since the latest update with beam. If I try to login to the bot using my beam account, it will not accept any of the other authentication methods, which, since my account was made through Microsoft means I cannot login at all. When you click on any of the other authentication buttons it opens another window, which remains completely blank. If you close that window the original login screen remains buffering until you close it. 

Just wondering if this issue has been identified, and if there are any fixes for it yet. Thanks!

**Comment by DeekyJay** [comment]
Hey Scaly! Thanks for reporting this issue. I've been looking into this we'll hopefully have a resolution shortly.

**Comment by spitfire1337** [comment]
@ScalySquash50  Even if your authenticated with MS, you can go to your account settings on beam and set a password, you'll then be able to log into soundboard using your MS email and password you set on beam
