### ISSUE TITLE
64bit will not run

### ISSUE THREAD

**Issue by XCdev** [Leviathan5/BeamSoundlyInteractive#7]
trying to open on windows 10 64bit app fails to load

**Comment by DeekyJay** [comment]
Can you run the application from the command prompt and see what the console logs?

**Comment by XCdev** [comment]
sorry I'm not good with the command prompt you will have to give me the commands

**Comment by DeekyJay** [comment]
Once you get to the directory, all you have to do is `start BeamSoundlyInteractive.exe`

Quickest way to navigate to this directory, SHIFT + Right Click in an area that is not a file, and click 'Open Command Window Here'

**Comment by XCdev** [comment]
![image](https://cloud.githubusercontent.com/assets/22665260/19164082/744636ea-8bf6-11e6-94a7-6de819a25ecd.png)
 freezes here

**Comment by DeekyJay** [comment]
Do you have a firewall / anti-virus running that could potentially be blocking the application?

**Comment by XCdev** [comment]
only what is built in to windows 10 but the 32bit version loads however throws an error when connecting yet it works on my laptop

**Comment by DeekyJay** [comment]
Have you tried running as Administrator?

**Comment by XCdev** [comment]
yeah

**Comment by DeekyJay** [comment]
Is the application perhaps running in the background?

**Comment by XCdev** [comment]
Not that I can tell how would I find out

**Comment by DeekyJay** [comment]
Task Manager -> Details

**Comment by XCdev** [comment]
just checked no its not
