### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by XCdev** [Leviathan5/BeamSoundlyInteractive#8]
![image](https://cloud.githubusercontent.com/assets/22665260/19162965/e441b4a6-8bf1-11e6-8c4a-dbbdf76886f6.png)

fails to connection on a wired connection

**Comment by ThatMFWolf** [comment]
i got the same problem. did you find a fix?

**Comment by XCdev** [comment]
yeh fixed by doing a full clean boot using msconfig if you need help drop by my channel and ill talk you through it or do it on stream good luck

**Comment by XCdev** [comment]
beam.pro/actitechuk

**Comment by DeekyJay** [comment]
With the new release of Soundwave Interactive, we will see if this issue has been resolved.
