### ISSUE TITLE
64bit Linux won't run on ubuntu 16.04

### ISSUE THREAD

**Issue by subzerokangaroo** [Leviathan5/BeamSoundlyInteractive#9]
Hi,

I've unpackaged the 64bit .zip but there is only a .exe file. I've tried running this through Wine but the application doessn't start.

**Comment by DeekyJay** [comment]
Have you attempted to run this application with the linux version? There is a linux build that doesn't need wine, and doesnt have an exe

**Comment by subzerokangaroo** [comment]
Ah! I was a little too click happy. Might be worth adding a cheeky text file chmod +x and run it from the terminal.

Thanks :)
